# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 15:53
from __future__ import unicode_literals

from django.db import migrations



def forwards_func(apps, schema_editor):
    Strategy = apps.get_model("gitload", "Strategy")
    db_alias = schema_editor.connection.alias
    Strategy.objects.using(db_alias).bulk_create([
        Strategy(name="python", json="{}", rel_path="/"),
    ])

def reverse_func(apps, schema_editor):
    Strategy = apps.get_model("gitload", "Strategy")
    db_alias = schema_editor.connection.alias
    Strategy.objects.using(db_alias).filter(name="python").delete()
    

class Migration(migrations.Migration):

    dependencies = [
        ('gitload', '0002_add_repository_data'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]

