site_name: Premier Langage
site_author: Q. Coumes, D. Revuz


pages:
- Home: 'index.md'
- Ecrire un exercice:
    - 'Bases': 'ecrire_pl.md'
    - 'Ecrire un formulaire': 'formulaire.md'
    - 'Ecrire une fonction d''évaluation': 'evaluator.md'
    - 'Ecrire une fonction build': 'build.md'
- Convertir .gift to .pl: 'plfromgift.md'

theme: null
theme_dir: custom

site_dir: ../templates/documentation/doc
